name: ADR Number Check
on:
  pull_request:
    paths:
      - 'decisions/**'
      - 'scripts/suggest-next-adr.sh'
permissions:
  contents: read
jobs:
  suggest-adr-number:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Suggest next ADR filename
        id: suggest
        continue-on-error: true ## This will allow the program to continue the job incase the ADR has failed the ADR number check 
        run: bash scripts/suggest-next-adr.sh --ci-suggest "${{ github.base_ref }}" ## This job will suggest the next ADR filename based on the ADR's that have already been merged in rhdh-adr:main

      - name: Fail if ADR numbering check failed 
        if: steps.suggest.outcome == 'failure'
        run: |
          echo "${{ steps.suggest.outputs.error }}"
          echo "${{ steps.suggest.outputs.suggestion }}"
          exit 1

    
    
